import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { z } from 'zod';
import { assertWritablePath, DESIGN_DIR } from './writeScope';
import type { ExtractedSystem } from '../extractor/DesignSystemExtractor';

/**
 * Persists extractor output to `.design/system/` (§6). Lives in
 * src/host/store/ because that is the only module allowed filesystem writes
 * (write-scope invariant); the extractor itself only reads.
 */

export const systemManifestSchema = z
  .object({
    schema_version: z.literal(1),
    generated: z.string(),
    sources: z.array(z.object({ path: z.string(), hash: z.string() }).strict()),
    stats: z
      .object({
        filesScanned: z.number(),
        durationMs: z.number(),
        truncated: z.boolean(),
        tokenCount: z.number(),
        componentCount: z.number(),
      })
      .strict(),
  })
  .strict();
export type SystemManifest = z.infer<typeof systemManifestSchema>;

const SYSTEM_DIR = path.join(DESIGN_DIR, 'system');

export class SystemStore {
  constructor(private readonly workspaceRoot: string) {}

  private resolve(relative: string): string {
    return assertWritablePath(this.workspaceRoot, relative);
  }

  async write(system: ExtractedSystem): Promise<void> {
    await fs.mkdir(this.resolve(SYSTEM_DIR), { recursive: true });
    await fs.writeFile(this.resolve(path.join(SYSTEM_DIR, 'tokens.css')), renderTokensCss(system), 'utf8');
    await fs.writeFile(
      this.resolve(path.join(SYSTEM_DIR, 'components.md')),
      renderComponentsMd(system),
      'utf8',
    );
    const manifest: SystemManifest = {
      schema_version: 1,
      generated: new Date().toISOString(),
      sources: system.sources,
      stats: {
        ...system.stats,
        tokenCount: system.tokens.length,
        componentCount: system.components.length,
      },
    };
    await fs.writeFile(
      this.resolve(path.join(SYSTEM_DIR, 'manifest.json')),
      JSON.stringify(manifest, null, 2) + '\n',
      'utf8',
    );
  }

  async readTokensCss(): Promise<string | null> {
    try {
      const css = await fs.readFile(path.join(this.workspaceRoot, SYSTEM_DIR, 'tokens.css'), 'utf8');
      return css.trim().length > 0 ? css : null;
    } catch {
      return null;
    }
  }

  async readManifest(): Promise<SystemManifest | null> {
    try {
      const raw = await fs.readFile(
        path.join(this.workspaceRoot, SYSTEM_DIR, 'manifest.json'),
        'utf8',
      );
      const parsed = systemManifestSchema.safeParse(JSON.parse(raw));
      return parsed.success ? parsed.data : null;
    } catch {
      return null;
    }
  }
}

function renderTokensCss(system: ExtractedSystem): string {
  const lines = [
    '/* Generated by Underpainting from this workspace — re-run “Underpainting: Extract Design System” to refresh. */',
    ':root {',
  ];
  for (const token of system.tokens) {
    lines.push(`  ${token.name}: ${token.value}; /* ${token.source} */`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

function renderComponentsMd(system: ExtractedSystem): string {
  const lines = [
    '# Component inventory',
    '',
    '_Heuristic extraction (names, props from source, cross-file usage counts) — no model involved (P3)._',
    '',
    '| Component | File | Props | Usages |',
    '|---|---|---|---|',
  ];
  for (const c of system.components) {
    lines.push(`| ${c.name} | ${c.file} | ${c.props.join(', ') || '—'} | ${c.usages} |`);
  }
  if (system.components.length === 0) {
    lines.push('| _none found_ | | | |');
  }
  lines.push('');
  return lines.join('\n');
}
